all: BerichtV46.pdf

BerichtV46.pdf: BerichtV46.tex
	lualatex BerichtV46.tex

BerichtV46.tex: Build/Theorie.tex

BerichtV46.tex: Build/Auswertung.tex

Build/Auswertung.tex:
	lualatex BerichtV46.tex

Berechnungen/
	pyhton
